/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.solonoblegame;

import java.awt.Color;
import java.awt.Component;
import java.awt.Font;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author berat
 */
public class BeratAlkinSoloNobleGameFrame extends javax.swing.JFrame {

    /**
     * Creates new form SoloNobleGameFrame
     */
    public BeratAlkinSoloNobleGameFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        pegsLeft = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        chosen_Peg = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAutoRequestFocus(false);
        setResizable(false);

        jPanel1.setPreferredSize(new java.awt.Dimension(850, 600));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("Welcome to Solo Noble Game!");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("In this game, a valid move is to jump a peg orthogonally over an adjacent peg into a hole two positions away and then to remove the jumped peg.");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("The more pegs you remove, the better score you will have. Good Luck!");

        jButton1.setText("Start");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 890, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 535, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(102, 102, 102)
                        .addComponent(jButton1)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jButton1))
                .addContainerGap(8, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 480, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("-");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setText("-");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setText("Pegs Left:");

        pegsLeft.setText("-");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("The Peg You Have Chosen:");

        chosen_Peg.setText("-");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setText("Node Log:");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addGap(6, 6, 6)
                            .addComponent(chosen_Peg))
                        .addComponent(jLabel4))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 378, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)
                            .addComponent(pegsLeft, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)))
                    .addComponent(jScrollPane2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chosen_Peg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addGap(60, 60, 60)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pegsLeft, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 902, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        BeratAlkinMultiLinkedList motherList = new BeratAlkinMultiLinkedList();
        //creating the multiLinkedList
        char column = 'A';
        char row = '1';
        for (int i = 0; i <= 8; i++) {
            String columnRow = String.valueOf(column) + String.valueOf(row++);
            motherList.addLast(columnRow);
            for (int x = 1; x <= 8; x++) {
                String columnRow2 = String.valueOf(column) + String.valueOf(row++);
                if ("D4".equals(columnRow2) || "D5".equals(columnRow2) || "E4".equals(columnRow2) || "E5".equals(columnRow2)) {
                    continue;
                }
                motherList.addLastContinue(columnRow2);
            }
            column++;
            row = '1';
        }
        //creating the gameboard. As you can see it is all done dynamically
        //i ran out of time to make the game resizable
        int x = 0;
        int y = 0;
        char column_ = 'A';
        char row_ = '1';
        for (int i = 1; i <= 64; i++) {
            JPanel innerPanel = new JPanel();
            innerPanel.setBounds(x, y, 60, 60);
            innerPanel.setLayout(null);

            //this label is used for getting the name of the board piece
            JLabel lbl = new JLabel(String.valueOf(column_) + String.valueOf(row_));
            lbl.setFont(new Font("Arial", Font.BOLD, 6));
            lbl.setBounds(0, 0, 8, 8);

            //this label indicates the peg
            JLabel lbl2 = new JLabel();
            ImageIcon png = new ImageIcon("red-circle.png");
            lbl2.setIcon(png);
            lbl2.setBounds(10, 10, 40, 40);

            x += 60;
            column_++;
            if (i % 8 == 0) {
                x = 0;
                y += 60;
                column_ = 'A';
                row_++;
            }
            if (i == 28 || i == 29 || i == 36 || i == 37) {
                lbl2.setVisible(false);
            }
            innerPanel.add(lbl);
            innerPanel.add(lbl2);
            innerPanel.setBackground(Color.LIGHT_GRAY);
            innerPanel.repaint();
            jPanel2.add(innerPanel);
            jPanel2.repaint();

            innerPanel.addMouseListener(new MouseAdapter() {
                //all of the game gets played in here.
                @Override
                public void mouseClicked(MouseEvent e) {
                    int x = e.getComponent().getX();
                    int y = e.getComponent().getY();
                    JLabel tempLbl = (JLabel) e.getComponent().getComponentAt(0, 0);
                    String clickedArea = tempLbl.getText();
                    //if the clicked area is green, it means that a move will happen.
                    if (e.getComponent().getBackground() == Color.GREEN) {
                        String data;
                        String chosenPeg = chosen_Peg.getText();
                        if (chosenPeg.charAt(0) == clickedArea.charAt(0)) {
                            if (clickedArea.charAt(1) - chosenPeg.charAt(1) == 2) {
                                data = String.valueOf(chosenPeg.charAt(0)) + String.valueOf((char) (chosenPeg.charAt(1) + 1));
                                motherList.add(clickedArea);
                                motherList.remove(data);
                                motherList.remove(chosenPeg);
                                e.getComponent().getComponentAt(10, 10).setVisible(true);
                                jPanel2.getComponentAt(x, y - 120).getComponentAt(10, 10).setVisible(false);
                                jPanel2.getComponentAt(x, y - 60).getComponentAt(10, 10).setVisible(false);
                            } else if (clickedArea.charAt(1) - chosenPeg.charAt(1) == -2) {
                                data = String.valueOf(chosenPeg.charAt(0)) + String.valueOf((char) (chosenPeg.charAt(1) - 1));
                                motherList.add(clickedArea);
                                motherList.remove(data);
                                motherList.remove(chosenPeg);
                                e.getComponent().getComponentAt(10, 10).setVisible(true);
                                jPanel2.getComponentAt(x, y + 120).getComponentAt(10, 10).setVisible(false);
                                jPanel2.getComponentAt(x, y + 60).getComponentAt(10, 10).setVisible(false);
                            }
                        } else {
                            if (clickedArea.charAt(0) - chosenPeg.charAt(0) == 2) {
                                data = String.valueOf((char) (chosenPeg.charAt(0) + 1) + String.valueOf(chosenPeg.charAt(1)));
                                motherList.add(clickedArea);
                                motherList.remove(data);
                                motherList.remove(chosenPeg);
                                e.getComponent().getComponentAt(10, 10).setVisible(true);
                                jPanel2.getComponentAt(x - 120, y).getComponentAt(10, 10).setVisible(false);
                                jPanel2.getComponentAt(x - 60, y).getComponentAt(10, 10).setVisible(false);
                            } else if (clickedArea.charAt(0) - chosenPeg.charAt(0) == -2) {
                                data = String.valueOf((char) (chosenPeg.charAt(0) - 1) + String.valueOf(chosenPeg.charAt(1)));
                                motherList.add(clickedArea);
                                motherList.remove(data);
                                motherList.remove(chosenPeg);
                                e.getComponent().getComponentAt(10, 10).setVisible(true);
                                jPanel2.getComponentAt(x + 120, y).getComponentAt(10, 10).setVisible(false);
                                jPanel2.getComponentAt(x + 60, y).getComponentAt(10, 10).setVisible(false);
                            }
                        }
                        Component[] comp = jPanel2.getComponents();
                        for (Component comp_ : comp) {
                            comp_.setBackground(Color.LIGHT_GRAY);
                        }
                        jLabel6.setText("Succesful move!");
                    } //if the clicked area is not green, it means that the moveable areas will get painted green
                    else {
                        Component[] comp = jPanel2.getComponents();
                        for (Component comp_ : comp) {
                            comp_.setBackground(Color.LIGHT_GRAY);
                        }
                        if (motherList.isThere(clickedArea)) {
                            chosen_Peg.setText(clickedArea);
                            int[] arr = motherList.Search(clickedArea);
                            if (arr[0] == 1) {
                                jPanel2.getComponentAt(x, y + 120).setBackground(Color.GREEN);
                            }
                            if (arr[1] == 1) {
                                jPanel2.getComponentAt(x, y - 120).setBackground(Color.GREEN);
                            }
                            if (arr[2] == 1) {
                                jPanel2.getComponentAt(x + 120, y).setBackground(Color.GREEN);
                            }
                            if (arr[3] == 1) {
                                jPanel2.getComponentAt(x - 120, y).setBackground(Color.GREEN);
                            }
                            jLabel5.setText("Please click an area to move the peg");
                        } else {
                            chosen_Peg.setText("-");
                            jLabel5.setText("Please click a peg to move");
                        }
                    }
                    jTextArea1.setText("");
                    //log update
                    jTextArea1.setText(motherList.print());
                    pegsLeft.setText(String.valueOf(motherList.getSize()));
                }
            }
            );
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BeratAlkinSoloNobleGameFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BeratAlkinSoloNobleGameFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BeratAlkinSoloNobleGameFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BeratAlkinSoloNobleGameFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BeratAlkinSoloNobleGameFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField chosen_Peg;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField pegsLeft;
    // End of variables declaration//GEN-END:variables
}
